### ISSUE TITLE
Australian Consumer Law Guarantees

### ISSUE THREAD

**Issue by micsthepick** [LoneDev6/Wiki-ItemsAdder#100]
**Describe the bug**
"No Refunds!
Refunds are possible only on particular cases and at the seller's discretion.
Contact the seller using the forum or via email before opening an official dispute on the payment platform (PayPal, Stripe etc.)."
The above is incorrect, as according to ACL, in "Competition and Consumer Act 2010, Part 3‑2—Consumer transactions
Division 1—Consumer guarantees
Subdivision A—Guarantees relating to the supply of goods"
and "Subdivision B—Guarantees relating to the supply of services"

**URLs of pages with problems**
- https://itemsadder.devs.beer/other/tos

**Expected behavior**
Refund policy:
Refunds are typically at the seller's discretion, except as required by applicable state law.

**Screenshots**
![image](https://github.com/LoneDev6/Wiki-ItemsAdder/assets/11528421/00991258-7891-4193-b004-2e795d320890)
![image](https://github.com/LoneDev6/Wiki-ItemsAdder/assets/11528421/f1790cc4-06a4-41fc-b2c8-6fb3a5478890)

**Comment by LoneDev6** [comment]
Thank you, done
