### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nanguo11** [LoneDev6/Wiki-ItemsAdder#57]
Server version: paper1.18.2
Client version:1.18.2
Plugin version 3.2.3-r10

Standing on the note box, you can copy items infinitely. Please watch the video

https://youtu.be/ZDXHkj4xaHE

**Comment by thefourcraft** [comment]
This is not the right place to report bugs... please go to the bag repo
https://github.com/PluginBugs/Issues-ItemsAdder/issues
@nanguo11 this is the wiki page...
