### ISSUE TITLE
[Suggestion] Clean up image names

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/Wiki-ItemsAdder#60]
The image names of this wiki are a mess to put it simple.

Not only are the names not giving any clue about what they are made for (What they display, which at least on GitHub is frustrating) but their names are also ugly (i.e. `image (27) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).png`)

In addition are some of the names so long that Git for Windows (And by extension GitHub Desktop) is unable to properly clone the repository as the length of the file name goes beyond the by default allowed length.
Even with that issue bypassed does it seem like there are files that seem to share the same name, but with different capitalization which Git doesn't like at all (See [MMICa0s.gif](https://github.com/Andre601/Wiki-ItemsAdder/blob/feature/better-emote-faq/.gitbook/assets/MMICa0s.gif) and its lowercase counter-part [mmica0s.gif](https://github.com/Andre601/Wiki-ItemsAdder/blob/feature/better-emote-faq/.gitbook/assets/mmica0s.gif)).

Because of all those issues should the assets folder receive a complete cleanup, as it otherwise makes it difficult if not even impossible to contribute towards the wiki itself.
If possible and supported by Gitbook should the images be put into folders to further separate them, allowing a much easier finding of them later on.

**Comment by thefourcraft** [comment]
we have like 600+ images that need to be removed, they ware created buy a bug...

**Comment by LoneDev6** [comment]
Yep, it's known, I might need to write a script that checks unused images and deletes them, then rename all current images to some sane names.

**Comment by LoneDev6** [comment]
Fixed
