### ISSUE TITLE
[BUG] %img_emojiname% returns icon + []

### ISSUE THREAD

**Issue by LoganTheOverlord** [LoneDev6/Wiki-ItemsAdder#61]
**Describe the bug**
When you parse any emoji/img placeholder within ItemsAdder, it returns the emoji itself, and [] afterwards with it.
Also, the default IA GUI is NOT WORKING. The IA GUI is broken, and shows [] also.

**To Reproduce**
1. Parse any font-image placeholder, or item.

**Expected behavior**
Emoji pops up in placeholder.

**Screenshots**
![image](https://user-images.githubusercontent.com/42440842/200427857-174d40b9-fbe8-4b67-93f8-38b243584314.png)
The GUI does not work also, nor does exist within IA namespaces, or is being contained within resourcepack.
![image](https://user-images.githubusercontent.com/42440842/200427948-89e2ad86-2596-46b9-b510-7b0f12c47808.png)

**Info (please complete the following information):**
 - Server version: LightSpigot 1.19.2
 - Client version: Vanilla 1.19.2, also Fabric/Sodium 1.19.2
 - Plugin version: ItemsAdder_3.2.5-r3
 

**Additional context**
Also happens on fresh install.
Very limiting in this area, sadly.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/huds-emojis-guis-font/characters#1.19-clients-show-instead-of-some-font-images

**Comment by LoneDev6** [comment]
Also note, this is not a place to report bugs about the plugin.
