### ISSUE TITLE
[BUG] error item has no texture after being hit

### ISSUE THREAD

**Issue by SharkblackFr** [LoneDev6/Wiki-ItemsAdder#63]
Hi,
error item has no texture after being hit
Here is the error in console : https://pastebin.com/gyPUSX0t

**Comment by thefourcraft** [comment]
# THIS IS NOT THE BUG-REPORTING PLACE!
# GO TO DISCORD AND MAKE A THREAD ABOUT YOUR ISSUE

**Comment by LoneDev6** [comment]
Report the issue here.
https://github.com/PluginBugs/Issues-ItemsAdder/issues
