### ISSUE TITLE
[BUG] LuckPerms DB Syncing Causing Items to Break

### ISSUE THREAD

**Issue by NIGHTMVRE** [LoneDev6/Wiki-ItemsAdder#65]
**Describe the bug**
I've noticed I was able to get my items all working successfully on my test server. I have a 3D head model that has custom model data and its base item is Minecraft paper. I can equip it to my head and everything works fine. When I transferred It to my main server, everything else works fine, but the 3D head item I can no longer equip to my head slot. After testing a bunch of different things I found that what makes or breaks it is whether my LuckPerms database config is set to H2 or my database. It works perfect as a H2, but when I set it to MariaDB and get it to connect and sync to my server (Which It needs to for my network perms to function right) it stops working, and It wont let me equip it to my head. Its textures are fine in my hand and in my inventory too. Very strange bug

**To Reproduce**
1. Set up ItemsAdder pack to have a 3D item that you can wear on your head
2. Add LuckPerms
3. Sync LuckPerms to a database
4. Restart the server
5. Notice that it doesn't work
6. Set the LuckPerms db back to H2
7. Restart server
8. Notcie that it works as it did before implementing luckperms

**Expected behavior**
You'd expect the item to behave as it would without luckperms, but when luckperms is synced via DB certain items are no longer equipable.

**Screenshots**
I don't think they are necessary, but if you'd like a demo I'd be happy to show you If requested.

**Info (please complete the following information):**
 - Server version: paper1.19.2
 - Client version: optifine 1.19.2
 - Plugin version: ItemsAdder_3.2.5-r3.jar

**Additional context**
None.

**Comment by LoneDev6** [comment]
This is not a place to report itemsadder bugs.

https://github.com/PluginBugs/Issues-ItemsAdder/issues
