### ISSUE TITLE
Animatedtitles

### ISSUE THREAD

**Issue by Arvinnnnnn** [LoneDev6/Wiki-ItemsAdder#73]
I would like to ask how this feature is used in the latest version of ItemsAdder, on Wiki I see it is old and not updated

**Screenshots**
![image](https://user-images.githubusercontent.com/97273150/221408748-155f220a-010d-4a26-b494-52ad368a0b2c.png)

**Comment by LoneDev6** [comment]
This is not the correct place to ask for help.
Anyway animated titles works fine on latest itemsadder.
