### ISSUE TITLE
[Request] Spanish branch

### ISSUE THREAD

**Issue by MrStreeet** [LoneDev6/Wiki-ItemsAdder#75]
Hello! As you have the Discord dm's and metions blocked in your server, is it possible to open a Spanish branch to translate the Wiki? It will be very helpful for the community

Thank you very much!

**Comment by LoneDev6** [comment]
Yes I can as soon as you think that you can actually on translating the wiki completely, thanks, let me know

**Comment by MrStreeet** [comment]
> Yes I can as soon as you think that you can actually on translating the wiki completely, thanks, let me know

Hello! Yes, I will transtale everything, sorry for late reply, I was on holidays ^^
