### ISSUE TITLE
I want to include your ItemsAdder plugin on my website

### ISSUE THREAD

**Issue by xybjs** [LoneDev6/Wiki-ItemsAdder#76]
(Use a translator to translate Chinese into English, causing you reading inconvenience, please understand) Hello, I am a MC server server owner in China, I use a lot of plugins, because the wiki is incomplete or not detailed, or difficult to understand, so I opened a website by myself plugins.icu He means, your plugin ICU, doesn't it sound quite interesting haha, I want to include your plugin in this website, so that more people can understand him, use this plugin! I ask you for permission, I will not share your jar file, and at the same time will mark the purchase location of spigotmc, so that more people know about ItemsAdder, if you can, please reply to me with the email address above! (463973701@qq.com)

**Comment by LoneDev6** [comment]
Hello please contact me on the forum using the `payment issue` category for this kind of inquiries.
Thanks.
https://forum.devs.beer/t/private-payment-issue

So we can discuss privately.

Also please provide more details about your project and what is it about.
