### ISSUE TITLE
Paper and purpur feature update

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/Wiki-ItemsAdder#80]
**Describe the bug**
A clear and concise description of what the issue is.
DO NOT REPORT PLUGIN BUGS. THIS IS ONLY FOR WIKI ISSUES.

Purpur lost some features because they were transferred to the paper itself https://github.com/PaperMC/Paper/commit/fead63e

**URLs of pages with problems**
- https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/avoid-glitched-blocks#optional-settings-on-purpur

**Expected behavior**

Information on what contains purpur and what contains paper will be updated

**Screenshots**

![image](https://github.com/LoneDev6/Wiki-ItemsAdder/assets/29830635/bf2b2734-9e32-4958-b9ae-e6977563cc76)

![image](https://github.com/LoneDev6/Wiki-ItemsAdder/assets/29830635/eaf775d3-6896-4a29-ae6b-a63b2b758545)

**Comment by LoneDev6** [comment]
Thanks I'll update this info
