### ISSUE TITLE
Andrebbe aggiunta un informazione.

### ISSUE THREAD

**Issue by Distolfix** [LoneDev6/Wiki-ItemsAdder#83]
https://itemsadder.devs.beer/faq/bungeecord-velocity/single-resourcepack-bungeecord

Caro @LoneDev6, in questa pagina andrebbe precisato che, non si può effettuare nel caso si usa l'external host quindi con pebbleshost. Questo motivo ricade perchè mi è successo che ogni tanto cambia il link di download della texturepack, quindi risulterebbe impossibile, effettuare un unico resourcpeack nel bungeecord. Io non lo sapevo, e mi sono ritrovato e impazzire e ho notato quindi che cambiano i link di download, e sarebbe disumano, che una persona ogni volta che fa iazip deve cambiare sempre link di download. Io metterei una precisazione come per esempio il metodo external host è vivamente sconsigliato perchè cambia spesso link di download, così persone come me non impazziscono. Spero aggiungerai questa dicitura 

P.S It's advised to use self-host, it's the best method.  so che lo hai scritto, però una persona non sapendolo, pensa che vada bene anche auto external host

**Comment by LoneDev6** [comment]
> Questo motivo ricade perchè mi è successo che ogni tanto cambia il link di download della texturepack

Non ho capito chi cambia il link, parli del sito che fa un redirect?
Mi sembra strano comunque, mai successo.

**Comment by Distolfix** [comment]
Il link di download della resourcepack mi è cambiato, quindi ho avuto problemi

**Comment by LoneDev6** [comment]
Ma cambiato in che modo?
Cambia solo se usi `/iazip`

**Comment by Distolfix** [comment]
Appunto, se ci pensi è altamente scomodo. Se io devo cambiare un file sulla texture implica che poi devo cambiare il link di download in tutti i server, sennò il plugin bungeecord resourcepack smette di lavorare. Poichè come sai, il plugin ha bisogno che in tutti i server abbiano lo stesso link. Quindi, se per esempio io con il metodo selfhost, ogni volta che faccio iazip in tutti i server non cambia il link, quindi mi basta sincronizzare solamente i file. Così facendo, è un casino. Io consiglierei di aggiungerlo, che è sconsigliato

**Comment by LoneDev6** [comment]
Grazie ho capito la problematica, lo scriverò chiaramente sulla wiki e ho in mente un aggiornamento per BungeePackFix che migliorerà questa funzionalità.

**Comment by LoneDev6** [comment]
Auto external hosting not working anymore
PloudOS is shutting down and I sadly have no control over it since I don't own the business.
Please use another hosting method instead since this one won't work anymore.

[Other hosting methods](https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting)
