### ISSUE TITLE
Default pack blocks (Modern Sandstone) right clickable.

### ISSUE THREAD

**Issue by pingarss** [LoneDev6/Wiki-ItemsAdder#88]
Blocks that use note block states to change textures are still right clickable by the players making the texture change back to a noteblock. It seems there may be an issue with the right click event that prevents this from not working efficiently.

This happened exactly with modern sandstone, but could be issue with any default packs blocks that are note blocks.

**Comment by LoneDev6** [comment]
1. this is not a place to report itemsadder issues, this is the wiki repository where people contribute to the docs of the plugin
2. i cannot help you without any information about you server + client and a video of the issue
3. this issue cannot be reproduced, custom blocks are not affected by right click, so there is something wrong.

Please provide the requested information in a proper issue report or it's impossible for me or anyone to help you.
thanks

https://github.com/PluginBugs/Issues-ItemsAdder/issues/
